baseurl: /Blog
title: Jot it down
subtitle: keep coding keep thinking
master:
  name: Your name
  about: Introduce yourself here
  email: Your E-mail
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: Copyrighter
  beginYear: 2011
  endYear: 2013
theme: default
codetheme: night
encoding: utf-8
markdown: kramdown